force-app/main/default/objects/Invoice_PDF__e/Invoice_PDF__e.object-meta.xml
<CustomObject>
    <label>Invoice PDF</label>
    <pluralLabel>Invoice PDFs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Invoice_PDF__e/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_PDF__e/fields/Related_Object_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_Object_Id__c</fullName>
    <label>Related Object Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InvoicePDFService.cls
public class InvoicePDFService {
        
    /*
     * this creates attachment records each Invoice_PDF__e record in the given list and attaches 
     * them to the related object specified in the Invoice_PDF__e event
	 */
    public static void SaveInvoicePDF(List<Invoice_PDF__e> incomingInvoicePDFs) {
        
        List<Attachment> attachmentsToInsert = new List<Attachment>();
        
        for(Invoice_PDF__e invoicePDF :incomingInvoicePDFs) {
            Attachment newAttachment = new Attachment();
            newAttachment.Body = EncodingUtil.base64Decode(invoicePDF.Invoice_PDF_Base64__c);
            newAttachment.ParentId = invoicePDF.Related_Object_Id__c;
            newAttachment.Name = 'Invoice - ' + invoicePDF.Invoice_Number__c + '.pdf';
            newAttachment.contentType = 'application/pdf';
            attachmentsToInsert.add(newAttachment); 
        }
        
        insert attachmentsToInsert;
        
    }

}