force-app/main/default/objects/Invoice_Response__e/Invoice_Response__e.object-meta.xml
<CustomObject>
    <label>Invoice Response</label>
    <pluralLabel>Invoice Responses</pluralLabel>
</CustomObject>

force-app/main/default/objects/Invoice_Response__e/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Response__e/fields/Invoice_PDF_Base64__c.field-meta.xml
<CustomField>
    <fullName>Invoice_PDF_Base64__c</fullName>
    <label>Invoice PDF Base64</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Invoice_Response__e/fields/Related_OppId__c.field-meta.xml
<CustomField>
    <fullName>Related_OppId__c</fullName>
    <label>Related OppId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InvoiceResponseService.cls
public class InvoiceResponseService {
    
    public static void SaveInvoiceResponse(List<Invoice_Response__e> responses) {
        
        List<Attachment> atts = new List<Attachment>();
        
        for(Invoice_Response__e response :responses) {
            Attachment att = new Attachment();
            att.Body = EncodingUtil.base64Decode(response.Invoice_PDF_Base64__c);
            att.ParentId = response.Related_OppId__c;
            att.Name = 'Invoice - ' + response.Invoice_Number__c + '.pdf';
            att.contentType = 'application/pdf';
            atts.add(att); 
        }
        
        insert atts;
        
    }

}